[package]
name = "wasm"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.152"
serde-wasm-bindgen = "0.4.5"
"wasm-bindgen" = "0.2.83"
